# Generated by Django 3.1.2 on 2021-04-28 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Behavior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial1', models.CharField(choices=[('R', 'Red'), ('B', 'Blue')], default=False, max_length=60, null=True)),
                ('trial2', models.CharField(choices=[('R', 'Red'), ('B', 'Blue')], default=False, max_length=60, null=True)),
                ('trial3', models.CharField(choices=[('R', 'Red'), ('B', 'Blue')], default=False, max_length=60, null=True)),
                ('trial4', models.CharField(choices=[('R', 'Red'), ('B', 'Blue')], default=False, max_length=60, null=True)),
                ('trial5', models.CharField(choices=[('R', 'Red'), ('B', 'Blue')], default=False, max_length=60, null=True)),
                ('trial6', models.CharField(choices=[('R', 'Red'), ('B', 'Blue')], default=False, max_length=60, null=True)),
                ('trial7', models.CharField(choices=[('R', 'Red'), ('B', 'Blue')], default=False, max_length=60, null=True)),
                ('trial8', models.CharField(choices=[('R', 'Red'), ('B', 'Blue')], default=False, max_length=60, null=True)),
                ('trial9', models.CharField(choices=[('R', 'Red'), ('B', 'Blue')], default=False, max_length=60, null=True)),
                ('trial10', models.CharField(choices=[('R', 'Red'), ('B', 'Blue')], default=False, max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=60)),
                ('lastname', models.CharField(max_length=60)),
                ('dob', models.DateField(null=True)),
                ('age', models.IntegerField(null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=False, max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('behavior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.behavior')),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1', to='polls.person')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2', to='polls.person')),
            ],
        ),
    ]
