# Generated by Django 3.1.2 on 2021-05-12 10:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_person_lastname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='age',
            new_name='Age',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='dob',
            new_name='DOB',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='firstname',
            new_name='FirstName',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='gender',
            new_name='Gender',
        ),
        migrations.AddField(
            model_name='person',
            name='LastName',
            field=models.CharField(default=django.utils.timezone.now, max_length=60),
            preserve_default=False,
        ),
    ]
